# Data manipulation with Numpy and Pandas

Handling large data in Python is very elegant. In the simplest way you can use plain arrays. However, they are pretty slow. Numpy and Panda are two great libraries for dealing with tabular datasets. Numpy is used for homogenous n-dimensional data (matrices). Pandas is used for heterogenous tables (CSV, MS Excel tables). Pandas is internally based on Numpy. See http://scipy-lectures.github.io/ for a more detailed tutorial.

In [1]:
import numpy as np

In [2]:
#generating a random array, values between 0 and 1 [0.0, 1.0)
X_rand = np.random.random((3, 5))  # a 3 x 5 array

print(X_rand)

[[0.8114643  0.45796764 0.14339386 0.87758884 0.72287385]
 [0.72799586 0.71542246 0.37130558 0.7416484  0.93526803]
 [0.68089484 0.23203732 0.9446918  0.8923062  0.9298998 ]]


In [3]:
#create 2D array, a 3 x 5 array
X = np.array([[15, 18, 22, 32, 45],    
              [13, 6, 17, 9, 20],   
              [21, 4, 49, 2, 8,]])   

print(X)

[[15 18 22 32 45]
 [13  6 17  9 20]
 [21  4 49  2  8]]


### Accessing elements

In [4]:
#get a single element, zero based indexing
X[0, 0]

15

In [5]:
#get a row
X[1]

array([13,  6, 17,  9, 20])

In [6]:
#get a column
X[:, 1]

array([18,  6,  4])

In [7]:
#transposing an array
X.T

array([[15, 13, 21],
       [18,  6,  4],
       [22, 17, 49],
       [32,  9,  2],
       [45, 20,  8]])

In [8]:
print(X.shape)
print(X.reshape(5, 3)) #change the layout of the matrix

(3, 5)
[[15 18 22]
 [32 45 13]
 [ 6 17  9]
 [20 21  4]
 [49  2  8]]


In [9]:
#indexing by an array of integers (fancy indexing)
indices = np.array([3, 1, 0])
print(indices)
X[:, indices]

[3 1 0]


array([[32, 18, 15],
       [ 9,  6, 13],
       [ 2,  4, 21]])

### Operations along an axis

In [10]:
X

array([[15, 18, 22, 32, 45],
       [13,  6, 17,  9, 20],
       [21,  4, 49,  2,  8]])

In [11]:
X.shape

(3, 5)

In [12]:
np.sum(X) # sum of all values

281

In [13]:
np.sum(X, axis=1) # 1...columns

array([132,  65,  84])

In [14]:
np.max(X, axis=0) # 0...rows

array([21, 18, 49, 32, 45])

## A quick-ish introduction to Pandas

based on http://pandas.pydata.org/pandas-docs/stable/10min.html

In [15]:
import numpy as np
import pandas as pd

In [16]:
#use a standard dataset of heterogenous data
cars = pd.read_csv('data/mtcars.csv')
cars.head()

car   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [17]:
#list all columns
cars.columns

Index(['car', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')

In [18]:
#we want to use the car as the "primary key" of a row
cars.index = cars.pop('car')
cars.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
car                                                                          
Mazda RX4          21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
Mazda RX4 Wag      21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
Datsun 710         22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

                   carb  
car                      
Mazda RX4             4  
Mazda RX4 Wag         4  
Datsun 710            1  
Hornet 4 Drive        1  
Hornet Sportabout     2

In [19]:
#describe our dataset
cars.describe()

mpg        cyl        disp          hp       drat         wt  \
count  32.000000  32.000000   32.000000   32.000000  32.000000  32.000000   
mean   20.090625   6.187500  230.721875  146.687500   3.596563   3.217250   
std     6.026948   1.785922  123.938694   68.562868   0.534679   0.978457   
min    10.400000   4.000000   71.100000   52.000000   2.760000   1.513000   
25%    15.425000   4.000000  120.825000   96.500000   3.080000   2.581250   
50%    19.200000   6.000000  196.300000  123.000000   3.695000   3.325000   
75%    22.800000   8.000000  326.000000  180.000000   3.920000   3.610000   
max    33.900000   8.000000  472.000000  335.000000   4.930000   5.424000   

            qsec         vs         am       gear     carb  
count  32.000000  32.000000  32.000000  32.000000  32.0000  
mean   17.848750   0.437500   0.406250   3.687500   2.8125  
std     1.786943   0.504016   0.498991   0.737804   1.6152  
min    14.500000   0.000000   0.000000   3.000000   1.0000  
25%    16.892500   0.000000   0.000000   3.000000   2.0000  
50%    17.710000   0.000000   0.000000   4.000000   2.0000  
75%    18.900000   1.000000   1.000000   4.000000   4.0000  
max    22.900000   1.000000   1.000000   5.000000   8.0000

In [20]:
cars.sort_index(inplace=True)
cars.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
car                                                                           
AMC Javelin         15.2    8  304.0  150  3.15  3.435  17.30   0   0     3   
Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3   
Camaro Z28          13.3    8  350.0  245  3.73  3.840  15.41   0   0     3   
Chrysler Imperial   14.7    8  440.0  230  3.23  5.345  17.42   0   0     3   
Datsun 710          22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   

                    carb  
car                       
AMC Javelin            2  
Cadillac Fleetwood     4  
Camaro Z28             4  
Chrysler Imperial      4  
Datsun 710             1

In [21]:
cars.sort_values('mpg').head(15)

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
car                                                                            
Cadillac Fleetwood   10.4    8  472.0  205  2.93  5.250  17.98   0   0     3   
Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3   
Camaro Z28           13.3    8  350.0  245  3.73  3.840  15.41   0   0     3   
Duster 360           14.3    8  360.0  245  3.21  3.570  15.84   0   0     3   
Chrysler Imperial    14.7    8  440.0  230  3.23  5.345  17.42   0   0     3   
Maserati Bora        15.0    8  301.0  335  3.54  3.570  14.60   0   1     5   
AMC Javelin          15.2    8  304.0  150  3.15  3.435  17.30   0   0     3   
Merc 450SLC          15.2    8  275.8  180  3.07  3.780  18.00   0   0     3   
Dodge Challenger     15.5    8  318.0  150  2.76  3.520  16.87   0   0     3   
Ford Pantera L       15.8    8  351.0  264  4.22  3.170  14.50   0   1     5   
Merc 450SE           16.4    8  275.8  180  3.07  4.070  17.40   0   0     3   
Merc 450SL           17.3    8  275.8  180  3.07  3.730  17.60   0   0     3   
Merc 280C            17.8    6  167.6  123  3.92  3.440  18.90   1   0     4   
Valiant              18.1    6  225.0  105  2.76  3.460  20.22   1   0     3   
Hornet Sportabout    18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

                     carb  
car                        
Cadillac Fleetwood      4  
Lincoln Continental     4  
Camaro Z28              4  
Duster 360              4  
Chrysler Imperial       4  
Maserati Bora           8  
AMC Javelin             2  
Merc 450SLC             3  
Dodge Challenger        2  
Ford Pantera L          4  
Merc 450SE              3  
Merc 450SL              3  
Merc 280C               4  
Valiant                 1  
Hornet Sportabout       2

In [22]:
cars.sort_values('hp', ascending=False).head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
car                                                                          
Maserati Bora      15.0    8  301.0  335  3.54  3.570  14.60   0   1     5   
Ford Pantera L     15.8    8  351.0  264  4.22  3.170  14.50   0   1     5   
Camaro Z28         13.3    8  350.0  245  3.73  3.840  15.41   0   0     3   
Duster 360         14.3    8  360.0  245  3.21  3.570  15.84   0   0     3   
Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3   

                   carb  
car                      
Maserati Bora         8  
Ford Pantera L        4  
Camaro Z28            4  
Duster 360            4  
Chrysler Imperial     4

## Selection

**Note**: While many of the NumPy accessor methods work on DataFrames, you can also use the optimized pandas-specific data accessor methods, `.at`, `.iat`, `.loc`, `.iloc` and `.ix`.

See the [Indexing section](http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing) and below.

In [23]:
#single column
cars['mpg']

car
AMC Javelin            15.2
Cadillac Fleetwood     10.4
Camaro Z28             13.3
Chrysler Imperial      14.7
Datsun 710             22.8
Dodge Challenger       15.5
Duster 360             14.3
Ferrari Dino           19.7
Fiat 128               32.4
Fiat X1-9              27.3
Ford Pantera L         15.8
Honda Civic            30.4
Hornet 4 Drive         21.4
Hornet Sportabout      18.7
Lincoln Continental    10.4
Lotus Europa           30.4
Maserati Bora          15.0
Mazda RX4              21.0
Mazda RX4 Wag          21.0
Merc 230               22.8
Merc 240D              24.4
Merc 280               19.2
Merc 280C              17.8
Merc 450SE             16.4
Merc 450SL             17.3
Merc 450SLC            15.2
Pontiac Firebird       19.2
Porsche 914-2          26.0
Toyota Corolla         33.9
Toyota Corona          21.5
Valiant                18.1
Volvo 142E             21.4
Name: mpg, dtype: float64

In [24]:
#or a slice of rows
cars[2:5]

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
car                                                                          
Camaro Z28         13.3    8  350.0  245  3.73  3.840  15.41   0   0     3   
Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3   
Datsun 710         22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   

                   carb  
car                      
Camaro Z28            4  
Chrysler Imperial     4  
Datsun 710            1

In [25]:
#by label = primary key
cars.loc['Fiat 128':'Lotus Europa']

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
car                                                                            
Fiat 128             32.4    4   78.7   66  4.08  2.200  19.47   1   1     4   
Fiat X1-9            27.3    4   79.0   66  4.08  1.935  18.90   1   1     4   
Ford Pantera L       15.8    8  351.0  264  4.22  3.170  14.50   0   1     5   
Honda Civic          30.4    4   75.7   52  4.93  1.615  18.52   1   1     4   
Hornet 4 Drive       21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
Hornet Sportabout    18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   
Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3   
Lotus Europa         30.4    4   95.1  113  3.77  1.513  16.90   1   1     5   

                     carb  
car                        
Fiat 128                1  
Fiat X1-9               1  
Ford Pantera L          4  
Honda Civic             2  
Hornet 4 Drive          1  
Hornet Sportabout       2  
Lincoln Continental     4  
Lotus Europa            2

In [26]:
#selection by position
cars.iloc[3]

mpg      14.700
cyl       8.000
disp    440.000
hp      230.000
drat      3.230
wt        5.345
qsec     17.420
vs        0.000
am        0.000
gear      3.000
carb      4.000
Name: Chrysler Imperial, dtype: float64

In [27]:
cars.iloc[3:5, 0:2]

mpg  cyl
car                         
Chrysler Imperial  14.7    8
Datsun 710         22.8    4

In [28]:
cars[cars.cyl > 6] # more than 6 cylinders

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
car                                                                            
AMC Javelin          15.2    8  304.0  150  3.15  3.435  17.30   0   0     3   
Cadillac Fleetwood   10.4    8  472.0  205  2.93  5.250  17.98   0   0     3   
Camaro Z28           13.3    8  350.0  245  3.73  3.840  15.41   0   0     3   
Chrysler Imperial    14.7    8  440.0  230  3.23  5.345  17.42   0   0     3   
Dodge Challenger     15.5    8  318.0  150  2.76  3.520  16.87   0   0     3   
Duster 360           14.3    8  360.0  245  3.21  3.570  15.84   0   0     3   
Ford Pantera L       15.8    8  351.0  264  4.22  3.170  14.50   0   1     5   
Hornet Sportabout    18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   
Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3   
Maserati Bora        15.0    8  301.0  335  3.54  3.570  14.60   0   1     5   
Merc 450SE           16.4    8  275.8  180  3.07  4.070  17.40   0   0     3   
Merc 450SL           17.3    8  275.8  180  3.07  3.730  17.60   0   0     3   
Merc 450SLC          15.2    8  275.8  180  3.07  3.780  18.00   0   0     3   
Pontiac Firebird     19.2    8  400.0  175  3.08  3.845  17.05   0   0     3   

                     carb  
car                        
AMC Javelin             2  
Cadillac Fleetwood      4  
Camaro Z28              4  
Chrysler Imperial       4  
Dodge Challenger        2  
Duster 360              4  
Ford Pantera L          4  
Hornet Sportabout       2  
Lincoln Continental     4  
Maserati Bora           8  
Merc 450SE              3  
Merc 450SL              3  
Merc 450SLC             3  
Pontiac Firebird        2

## Missing data

In [29]:
cars_na = pd.read_csv('data/mtcars_with_nas.csv')

In [30]:
cars_na.isnull().head(4)

car    mpg    cyl   disp     hp   drat     wt   qsec     vs     am  \
0  False  False  False  False  False  False  False  False  False  False   
1  False  False  False   True  False  False  False  False  False  False   
2  False  False  False  False  False  False  False  False  False  False   
3  False  False  False  False  False  False  False  False  False  False   

    gear   carb  
0  False  False  
1  False  False  
2  False  False  
3  False  False

In [31]:
#fill with a default value
cars_na.fillna(1).head(4)

car   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0       Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1   Mazda RX4 Wag  21.0    6    1.0  110  3.90  2.875  17.02   0   1     4   
2      Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3  Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   

   carb  
0     4  
1     4  
2     1  
3     1

In [32]:
#or drop the rows

print(cars_na.shape)
#drop rows with na values
print(cars_na.dropna().shape)
#drop columns with na values
print(cars_na.dropna(axis=1).shape)

#see also http://pandas.pydata.org/pandas-docs/stable/missing_data.html

(32, 12)
(29, 12)
(32, 10)


## Statistics

In addition to `.describe()` there are plenty of other staticial measures and aggregation methods in Pandas/Numpy.

In [33]:
#stats
cars.mean()

mpg      20.090625
cyl       6.187500
disp    230.721875
hp      146.687500
drat      3.596563
wt        3.217250
qsec     17.848750
vs        0.437500
am        0.406250
gear      3.687500
carb      2.812500
dtype: float64

In [34]:
cars.mean(axis=1)

car
AMC Javelin            46.007727
Cadillac Fleetwood     66.232727
Camaro Z28             58.752727
Chrysler Imperial      65.972273
Datsun 710             23.598182
Dodge Challenger       47.240909
Duster 360             59.720000
Ferrari Dino           34.508182
Fiat 128               19.440909
Fiat X1-9              18.928636
Ford Pantera L         60.971818
Honda Civic            17.742273
Hornet 4 Drive         38.739545
Hornet Sportabout      53.664545
Lincoln Continental    66.058545
Lotus Europa           24.880273
Maserati Bora          63.155455
Mazda RX4              29.907273
Mazda RX4 Wag          29.981364
Merc 230               27.233636
Merc 240D              24.634545
Merc 280               31.860000
Merc 280C              31.787273
Merc 450SE             46.430909
Merc 450SL             46.500000
Merc 450SLC            46.350000
Pontiac Firebird       57.379545
Porsche 914-2          24.779091
Toyota Corolla         18.814091
Toyota Corona          24.888636
Valian

In [35]:
#grouping
cars.groupby('cyl').mean()

mpg        disp          hp      drat        wt       qsec  \
cyl                                                                     
4    26.663636  105.136364   82.636364  4.070909  2.285727  19.137273   
6    19.742857  183.314286  122.285714  3.585714  3.117143  17.977143   
8    15.100000  353.100000  209.214286  3.229286  3.999214  16.772143   

           vs        am      gear      carb  
cyl                                          
4    0.909091  0.727273  4.090909  1.545455  
6    0.571429  0.428571  3.857143  3.428571  
8    0.000000  0.142857  3.285714  3.500000

In [36]:
#grouping different aggregation methods
cars.groupby('cyl').agg({ 'mpg': 'mean', 'qsec': 'min'})

mpg  qsec
cyl                 
4    26.663636  16.7
6    19.742857  15.5
8    15.100000  14.5

## TASKS

In [37]:
#loading gapminder data (taken from https://github.com/jennybc/gapminder)
#file located at 'data/gapminder-unfiltered.tsv' it uses tabular character as separator
#use the first column as index

In [38]:
#what are the columns of this dataset?

In [39]:
#what is the maximal year contained?

In [40]:
#just select all data of the year 2007

In [41]:
#locate Austria and print it

In [42]:
#list the top 10 countries by life expectancy (lifeExp)

In [43]:
#what is the total population (pop) per continent

## Next

[Static Plotting using Matplotlib and Seaborn](03_StaticPlotting.ipynb)